### ISSUE TITLE
[Bug] dbt_utils version conflict

### ISSUE THREAD

**Issue by pixie79** [dbt-labs/dbt_metrics#139]
### Is this a new bug in dbt_metrics?

- [X] I believe this is a new bug in dbt_metrics
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

when trying to do a dbt deps I get an error saying 

Version error for package dbt-labs/dbt_utils: Could not find a satisfactory version from options: ['>=0.9.2', '>=0.9.0', '<1.0.0', '>=0.8.1', '<0.9.0']

### Expected Behavior

DBT metrics should be installed ok

### Steps To Reproduce

packages:
  - package: dbt-labs/spark_utils
    version: [">=0.3.0"]
  - package: dbt-labs/dbt_utils
    version: [">=0.9.2"]
  - package: calogica/dbt_expectations
    version: [">=0.6.1", "<0.7.0"]
  - package: calogica/dbt_date
    version: [ ">=0.6.0", "<0.7.0" ]
  - package: dbt-labs/dbt_external_tables
    version: [">=0.8.0"]
  - package: dbt-labs/metrics
    version: [ ">=0.3.0", "<0.4.0"]

### Environment

```markdown
- dbt-adapter & version:
- dbt_metrics version: v0.3.6
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

dbt-glue

**Comment by callum-mcdata** [comment]
Hi @pixie79 ! This isn't a bug as much as it is a known version conflict. The 0.3.x minor version of dbt_metrics only supports `[">=0.8.0", "<0.9.0"]` of dbt_utils - it doesn't contain the upgrade to `0.9.x`, which is coming out as part of the next release.

**Comment by suryapatnaik1** [comment]
Hi @callum-mcdata - I tried with dbt_utils  [">=0.8.0", "<0.9.0"] and dbt-labs/metrics as  [ ">=0.3.0", "<0.4.0"], ran into the error below

  dbt.exceptions.DependencyException: Version error for package dbt-labs/dbt_utils: Could not find a satisfactory version from options: ['>=0.8.0', '<0.9.0', '>=0.9.0', '<1.0.0', '>=0.8.1', '<0.9.0'].

**Comment by callum-mcdata** [comment]
Hi @suryapatnaik1 - I think you might have another package that is trying to install a different version of dbt_utils? Additionally metrics installs utils as part of its dependency so you wouldn't need to have it in your `packages.yml`.

Are you also trying to install other packages or just those two?

**Comment by pixie79** [comment]
I have found the conflict - it appears to be in the  
 - package: calogica/dbt_expectations
    version: [">=0.6.0", "<0.7.0"]

Which in turn requires:
  - package: calogica/dbt_date
    version: [ ">=0.6.0", "<0.7.0" ]

Do you have a rough eta on when you are expecting the new release?

**Comment by callum-mcdata** [comment]
@pixie79 the new version has been released! As such, I will close out this issue.
