### ISSUE TITLE
[SEMANTIC-87] [Feature] Enable Unbounded Rolling Secondary Calculation

### ISSUE THREAD

**Issue by andresrecalde** [dbt-labs/dbt_metrics#140]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

For the [Rolling Secondary Calculation](https://github.com/dbt-labs/dbt_metrics#rolling-source), I propose `interval` can be optionally None which would default the window frame of the function to `rows between unbounded preceding and current row`. In this scenario, the aliased metric name would simply be `rolling_[metric_name]`.

### Describe alternatives you've considered

I'm currently overriding the macro(s) to enable `unbounded` to be injected rather than `interval - 1` to enable this. I considered injecting a larger integer, but Snowflake limits the window frame to 1000 rows when it's specified. I also considered doing this via the BI layer, but that would require including all metric data in the view (i.e. can't be filtered) and would be difficult to maintain.

### Who will this benefit?

For many metrics, a complete cumulative view over time is incredibly valuable (ex. subscriber count). 

### Are you interested in contributing this feature?

Yes, I can contribute to complete this

### Anything else?

From what I can tell, updates would be needed: 

- [ ] [Readme Documentation](https://github.com/dbt-labs/dbt_metrics#rolling-source)
- [ ] [Actual Rolling Calculation Generation](https://github.com/dbt-labs/dbt_metrics/blob/main/macros/secondary_calculations/secondary_calculation_rolling.sql)
- [ ] [Configuration Validation](https://github.com/dbt-labs/dbt_metrics/blob/main/macros/secondary_calculations_configuration/rolling.sql)
- [ ] [Alias Generation](https://github.com/dbt-labs/dbt_metrics/blob/main/macros/secondary_calculations/generate_secondary_calculation_alias.sql)

The Configuration Validation could use updating since it's using the incorrect terminology for the existing error message (it says `period_over_period` rather than `rolling`).

**Comment by callum-mcdata** [comment]
@andresrecalde just getting around to this after Coalesce - I think this is definitely something we'd consider for a future release! If you're still interested in contributing to this, I'd love to help provide you direction to get it merged for a future patch version.

I think you've got a pretty good handle of all then work that would need to be done. All the areas you laid out are exactly where I would have pointed you otherwise!

**Comment by andresrecalde** [comment]
Thanks @callum-mcdata! I'm happy to contribute here; let me know how to proceed!

**Comment by callum-mcdata** [comment]
Lovely! Apologies if you're familiar with contributing to dbt Labs repos but I'll lay out all the steps just in case you're not.
1. Create a fork of this repo in your github account. 
2. Create a branch in that fork with whatever name is relevant to the feature you're adding
3. Add all the code that you need to accomplish it (more on this below)
4. Add a pytest file to confirm that this behavior matches what you expect (I can walk you through this as well!)
5. Open a PR from your forked branch into the `main` branch of this repo!
6. Wait for me to review 🚀 

For the actual code changes, I think you had a pretty good handle in all of the files that you raised in your initial issue. I think the changes you suggested to those line up with what we'd be looking for and I could offer any guidance if you run into blockers!

Does that sound good to you?

**Comment by callum-mcdata** [comment]
@andresrecalde just checking in to see if you've been able to make any progress in this area!

**Comment by callum-mcdata** [comment]
@andresrecalde I hope you don't mind but I had some time this week allocated to the metrics package and decided this was a good thing to work on! I've got an open PR here #186 that should merge in today and be in tomorrow's release.

Hopefully the excitement over the release is bigger than the bummer of not contributing on this! If you're interested in contributing on any other area I'm more than happy to work with you and set up a project. The reason I picked this is because it was one I'd heard requested by some other community members so I figured sooner was better!

**Comment by andresrecalde** [comment]
Hey @callum-mcdata, so sorry I missed these messages; it's been a hectic few weeks! I haven't had a second to work on this, so very excited it's making it in!

**Comment by callum-mcdata** [comment]
No need to apologize, I totally understand! This PR should be merged in by midday and then be part of the 1.3.2 release later today! The TLDR is that `interval` is now an optional input and if no interval is provided then it defaults to an unbounded rolling calc.
