### ISSUE TITLE
[Feature] Support vars/jinja in metrics expressions

### ISSUE THREAD

**Issue by saraleon1** [dbt-labs/dbt_metrics#147]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

[Being able to support vars](https://docs.getdbt.com/reference/dbt-jinja-functions/var) (or jinja more generally) in metrics expression (ex: [derived expressions](https://docs.getdbt.com/docs/build/metrics#derived-metrics)) would allow more bespoke use cases that allow us to modify some metric SQL based on user input. This could make metrics more flexible, allowing for one metric to be used in many cases.  Some use cases may be to allow for top n performing product comparisons, or dynamic date ranges.

### Describe alternatives you've considered

We considered keeping these dynamic metrics in other layers (ex: BI)

### Who will this benefit?

Users who want more flexibility in the logic you can use in metrics; Users who want to fully define all metrics in dbt, rather than having to keep some metrics in tools that support dynamic input.

**Comment by callum-mcdata** [comment]
@saraleon1 thank you for opening up this issue, it is an interesting topic! When I imagine a world where arbitrary vars/jinja are supported in metric definitions, it feels like a dangerous path to begin walking down. One of the tenets of metrics is `A metric value should be consistent everywhere that it is referenced`. This design path feels that it could very easily break this tenet.

#### Example
Let's say we have the following metric definition in a world where `expression` can support variables
```yml
version: 2
metrics:
  - name: revenue
    model: ref('revenue')

    calculation_method: sum
    expression: case when segment = {{var('segment'}} then amount else 0 end
```
Depending on what is provided as the variable, we'd be returning completely different results.

I think I fall in the camp that I'd love to encourage more flexibility with macro inputs and/or metric configuration options (like overriding nulls with 0's, etc) as opposed to opening up the world to jinja in metric calculations.

Does that align with your world view?
