### ISSUE TITLE
[Bug] GitHub Actions: Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by kevinneville** [dbt-labs/dbt_metrics#163]
### Is this a new bug in dbt_metrics?

- [X] I believe this is a new bug in dbt_metrics
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

GitHub Actions: Deprecating save-state and set-output commands, these should be replaced with the proposed solution.
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

### Expected Behavior

We should not see the warnings.

### Steps To Reproduce

Run all GH checks.

### Environment

```markdown
- dbt-adapter & version:
- dbt_metrics version:
```

**Comment by callum-mcdata** [comment]
Closed out with #213!
