### ISSUE TITLE
[SEMANTIC-59] [Bug] metric_jsonschema_example still references old properties in required fields

### ISSUE THREAD

**Issue by rijnhardtkotze** [dbt-labs/dbt_metrics#176]
### Is this a new bug in dbt_metrics?

- [X] I believe this is a new bug in dbt_metrics
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently, the [metric_jsonschema_example.json](https://github.com/dbt-labs/dbt_metrics/blob/d3aadb161c81b0d7743088f4c903e86cc6fb7490/examples/metric_jsonschema_example.json#L4) file still references the `type` and `sql` properties.

```yml
    "required": ["name","label","timestamp","time_grains","type","sql"],
```

### Expected Behavior

It should be updated with the new properties, `calculation_method` and `expression`

### Steps To Reproduce

1. View the source [here](https://github.com/dbt-labs/dbt_metrics/blob/d3aadb161c81b0d7743088f4c903e86cc6fb7490/examples/metric_jsonschema_example.json#L4)

### Environment

```markdown
main branch
```

### Additional Context

Happy to submit a PR to fix this.

**Comment by rijnhardtkotze** [comment]
I am happy to submit a PR to fix this if required.

**Comment by callum-mcdata** [comment]
@rijnhardtkotze I'm happy to take this on and fix this quickly but if you want to take it on, you're more than welcome! Always love to get community PR's!

**Comment by rijnhardtkotze** [comment]
I would like to submit the PR, if you do not mind. I am just about ready to create it. Keen to make my first PR for OSS.

**Comment by callum-mcdata** [comment]
Love it! Tag me as a reviewer once you submit it and happy to work with you on getting it over the line!

**Comment by rijnhardtkotze** [comment]
[https://github.com/dbt-labs/dbt_metrics/pull/177](Here) is the PR: @callum-mcdata (I can't seem to tag you as a reviewer, for some weird reason)
