### ISSUE TITLE
[SEMANTIC-207] I should be able to have the ability to get the first and last value in a period

### ISSUE THREAD

**Issue by rijnhardtkotze** [dbt-labs/dbt_metrics#224]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Just like there is a mechanism to get the median for a period in a metric calculation, you should be able to get the first or last value of a period as well.

### Describe alternatives you've considered

There are no alternatives that I can think of

### Who will this benefit?

Analytics Engineers who are wanting to find the value of a metric and the start and end of the period. 

Use Cases that I can think of:
- Membership at the start of the month / week / quarter / year
- Membership at the end of the month / week / quarter / year
- Membership growth (derived metric from the top two)

### Are you interested in contributing this feature?

Yes

**Comment by rijnhardtkotze** [comment]
From what I can tell, it would need a change here: macros/sql_gen/gen_primary_metric_aggregate.sql

**Comment by williamxnguyen** [comment]
@rijnhardtkotze

Is a better approach to this problem to simply:
1. Configure a custom date calendar for your `dbt-project`?
2. Ensure your custom calendar contains date-fields `date_first_day_of_quarter`, `date_last_day_of_quarter` etc.
3. Configure a list of custom date variables to slice your metrics by within `time-grain` configuration of metrics. 

What do you think?

**Comment by callum-mcdata** [comment]
Hey folks! Appreciate y'all opening the issue. @rijnhardtkotze is right here in that this would require adding a new aggregation type for the best results. Unfortunately we're planning on working on any new aggregation issues at the moment as the team is focusing on integrating MetricFlow into the Semantic Layer.

If y'all wanted to take this on you're more than welcome though!

**Comment by callum-mcdata** [comment]
Hey @rijnhardtkotze ! I am closing out this issue out because of our deprecation announcement here: https://docs.getdbt.com/blog/deprecating-dbt-metrics. Future development of the Semantic Layer will be moving over to https://github.com/dbt-labs/metricflow with the release of dbt-core 1.6 in July 2023.
