### ISSUE TITLE
[Feature] Add support for dbt-core 1.6

### ISSUE THREAD

**Issue by philippeboyd** [dbt-labs/dbt_metrics#252]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

What the title says.

### Who will this benefit?

The DBT community that keeps their dependencies up to date.

### Anything else?

@callum-mcdata would you know if this support be complicated to implement?

**Comment by callum-mcdata** [comment]
@philippeboyd I am no longer with dbt Labs but this package was deprecated with version 1.5 of dbt. I recommend looking at that repo & the dbt documentation around this migration.

**Comment by philippeboyd** [comment]
Hi @callum-mcdata, guess I missed that; apologies. Indeed I stumbled upon this [new doc page](https://docs.getdbt.com/docs/build/metrics). I'll have a look at Metricflow.

Thanks for the heads up!
