### ISSUE TITLE
Adopting Pytest 

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt_metrics#45]
With @dbeatty10 working on a framework for package maintainers to begin introducing pytest into their development cycle, we're presented with an opportunity to beta-test it for something we'd been planning on implementing in the first place!

### Why Pytest?
Right now, dbt tests confirm that things are still working but they can't test that expected failure testing. Pytest allows us to introduce errors that we WANT to fail and then test that we're getting the result we want to see.

**Comment by dbeatty10** [comment]
🤩

Currently, this repo is the easiest way I know of to see how the dbt pytest'ing framework works:
https://github.com/dbt-labs/dbt-tests-adapter-custom-tests

If I come across or build anything better, I'll try to remember to update this ticket.
