### ISSUE TITLE
Development Workflow - Develop/Test Metric Function?

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt_metrics#66]
### Description
After discussions with a few different partners, we've realized that the metrics implementation right now is very focused on `production` use cases. Which is great! This is where business consumers are going to see them and its the highest importance to ensure that they're experience is delightful.

**However**, its also important for us to have a delightful experience for the developer adding metrics to a project. Right now, developers can define a metric in a dbt project and then run a model with the `calculate` macro but this creates temporary objects for the sake of testing/validation. Bit of an anti-pattern. 

Additionally, it doesn't fit in nicely with dbt Server, which runs based on the production code manifest. 

### Proposal
Add additional functionality that would take in a yml definition (defined in some jinja block) and calculate parameters, and then returns the dataset. This could be used in the future in query editors in order to test out metrics or even test alternate definitions to see how they change. 

**Potential Implementation**:
```
{% set metric_definition %}
metrics:
  - name: abc
    ...
{% endset %}
{{ metrics.develop(definition=metric_definition, <calculate params>) }}
```

**Comment by callum-mcdata** [comment]
All righty, after talking with @jtcohen6 he suggested that we might be able to use `fromyaml` and a bit of tom foolery to set this up. The biggest blocker, however, is that wouldn't be able to support nested `expression` metrics. Given that expression metrics rely heavily on the compiled `graph` variable and that there's no way to inject temporary yml files to be compiled into a new graph, it becomes impossible to temporarily model multiple metrics in the proposed macro.

I believe that this is a fine tradeoff and actually reduces the likelihood of someone continually adding more metrics to this functionality to support their use cases. Metrics should always be centralized - this macro should support testing but not Shadow DAGs.

**Comment by callum-mcdata** [comment]
This means that an implementation of this would look like:

```sql
{% set my_metric_yml -%}

metrics:
  - name: base_average_metric
    model: ref('fact_orders')
    label: Total Discount ($)
    timestamp: order_date
    time_grains: [day, week, month]
    type: average
    sql: discount_total
    dimensions:
      - had_discount
      - order_country

{%- endset %}

select * 
from {{ metrics.develop(yml=my_metric_yml, <calculate params>) }}

```

Then inside of the macro, we'd set the variables of the metric definition like:

```
{% set grains = yml['metrics']['time_grains'] %}
```

**Comment by joellabes** [comment]
Yes I'm very into this!
