### ISSUE TITLE
[Bug] metrics.calculate crashes when model `ref` in metric definition uses double quotes 

### ISSUE THREAD

**Issue by glqstrauss** [dbt-labs/dbt_metrics#75]
### Is this a new bug in dbt_metrics?

- [X] I believe this is a new bug in dbt_metrics
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When a dbt `metric` definition's `model` field specifies a `ref` using double quotes (for example, `model: ref("bookings")`, `metrics.calculate` crashes while attempting to fetch the model relation during the `dbt compile` stage (log output below).

### Expected Behavior

Double-quotes in a `ref` should be supported.
`dbt-core` compiles successfully when a `ref` is specified with double quotes, whether in a metric definition, or a jinja block. It seems reasonable that double quotes should be accepted, as it is valid python syntax.

### Steps To Reproduce

Can't share my company's code but would recommend trying to reproduce by modifying a fixture to use double-quotes in a metric definition's `model` field. I tried to reproduce it this way but it was taking a bit too long to get my local environment in a state that made pytest happy.

### Relevant log output

```shell
dbt.exceptions.RuntimeException: Runtime Error
  Compilation Error in model average_booking_value (models/metrics/average_booking_value.sql)
    No first item, sequence was empty.
    
    > in macro get_metric_sql (macros/get_metric_sql.sql)
    > called by macro default__calculate (macros/calculate.sql)
    > called by macro calculate (macros/calculate.sql)
    > called by macro get_model_relation (macros/graph_parsing/get_model_relation.sql)
    > called by model average_booking_value (models/metrics/average_booking_value.sql)
15:04:59  Encountered an error:
Runtime Error
  Compilation Error in model average_booking_value (models/metrics/average_booking_value.sql)
    No first item, sequence was empty.
    
    > in macro get_metric_sql (macros/get_metric_sql.sql)
    > called by macro default__calculate (macros/calculate.sql)
    > called by macro calculate (macros/calculate.sql)
    > called by macro get_model_relation (macros/graph_parsing/get_model_relation.sql)
    > called by model average_booking_value (models/metrics/average_booking_value.sql)
```
```


### Environment

```markdown
- dbt-adapter & version: v1.2.0
- dbt_metrics version: v0.3.1
```

### Which database adapter are you using with dbt?

snowflake

**Comment by callum-mcdata** [comment]
Hey @glqstrauss ! This is interesting - I suspect this is coming from some of the logic on how we loop through multiple metrics. Appreciate you flagging it!

I'll add it to the backlog to try and resolve but in the meantime does switching to single quotes work for you?

**Comment by glqstrauss** [comment]
Yep, switching to single quotes is not a problem, just figured I'd flag. Thanks!

**Comment by callum-mcdata** [comment]
@glqstrauss @dave-connors-3 valiantly leaped in here and tackled this issue - we'll get this out in the next release (0.3.2) in the coming weeks!
