### ISSUE TITLE
[Feature] Consider renaming the package

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt_metrics#81]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

A contributor wrote this code: 

```
select * from {{ metric.calculate(
    metric=metric('items_sold'),
    grain='week',
    dimensions=[]
) }}
```

and when compiling got this error: 

```
dbt.exceptions.RuntimeException: Runtime Error
  Compilation Error in analysis test_metrics (analyses/test_metrics.sql)
    'dbt.context.providers.RuntimeMetricResolver object' has no attribute 'calculate'. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
01:09:55  Encountered an error:
Runtime Error
  Compilation Error in analysis test_metrics (analyses/test_metrics.sql)
```

The reason is that they invoked `metric.calculate()` not `metricS.calculate()`. `metric` is a dbt Core construct, like `ref`, and `metrics` is the name of the package. 

It would be less possible to make this mistake if we renamed the package, e.g. to `dbt_metrics`. This would also probably help with googling in the future because dbt_metrics isn't as polluted a namespace. (see also the poor sods who are trying to search how to do something using R)

### Describe alternatives you've considered

- Doing nothing. 
- Creating a package called `ref` to maximise chaos in the world. 

### Who will this benefit?

People who are trying to write code at 6pm and can't remember where the S's go

This will explicitly cause pain for people integrating against the package, so if we're going to do it we should do it ASAP.

**Comment by callum-mcdata** [comment]
Directionally I'm on board - I think it makes sense for it to better match our other packages (dbt_utils) and prevent the namespacing issue. **However**, I'm worried that changing the syntax again after just recently changing the macro name to `calculate` would be a large ask of all the partners who are working with us. 

Would it make more sense for us to table this one and then combo it with a future syntax change?

**Comment by joellabes** [comment]
I agree that it is inconvenient - it would have been better to get both changes in at the same time. But if we're going to change it, infinitely better to do so _before_ GA. Right now it's annoying - once people are using it in production it's probably impossible without jumping through backward compatibility hoops. 

Sooo if you're anticipating any other changes in the next 2 months that we could bundle with, sure! But if not then I say we bite the bullet

**Comment by callum-mcdata** [comment]
@drewbanin what are your thoughts here - it would be another change that partners would have to implement but @joellabes has the very good point of better now than much later once the syntax is generally available in the semantic layer.

The only changes we have for the package before Coalesce are the current issues and none of those strike me as being a full version jump from 0.3.0 to 0.4.0.

**Comment by callum-mcdata** [comment]
We have decided against this for the time being in order to ensure a consistent querying experience for our integration partners. Closing for now.
