### ISSUE TITLE
[Feature] Metrics Should Support Rolling/Window Metrics

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt_metrics#83]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Right now, metrics are aggregations applied to the underlying dataset grouped upon dimensions and the provided time grain. But this is a simplistic view of metrics - it excludes metrics that exist across a rolling range of time.

**Example**:
- Weekly Active Users: Right now, metrics handles this perfectly well. 
- Rolling 14D Active Users: This is not supported

**Why Would A Company Use Rolling Window Metrics?**
There are certain usage patterns for products that have natural ebbs and flows based on inconsistent time ranges. Weekly metrics might be unreliable but a rolling 14d average might be a better representation of the health of the metric. Given this, we should expand our definition of metrics to support these ones as well.

### Implementation
From early mock-ups, I believe this could require one new components of the metric definition. Note I am not married to these names and think they should be called something else:
- Interval: the number of days that the metric should look back. Ex: 14

**NOTE**: I am proposing that we tie this lookback functionality directly to days. The aggregation **could** still possibly be different 

These would live in the metric definition.

### Open Questions
- We **strongly believe** that the lookback window is part of the metric definition itself. This helps us keep our guiding tenet of a metric value should be consistent everywhere that it is referenced
  - **Example**: Right now our strong thinking is that any lookback is itself part of the metric definition - if you want 30D average instead of 14D then that would be a different metric.
  - Should this be implicit in the metric definition? I'd love to hear counterpoints if people have them!
- We **believe** that these lookbacks should be expressed in days, weeks, months, years.
  - How do people think about lookback metrics? I've always defined them in terms of days (14d, 30d, 90d, etc) but I know there are use cases for other time grains like month. Quarter is too nebulous and not a supported datetime format so I believe that should be excluded. Thoughts?
- We **believe** that time grains at higher levels than day represent the desire to see the metric on that grain (week, month), not double aggregations to that level
  - **Example**: Your metric is 30D lookback and you select the week grain when aggregating your metric. What you're really asking is to see the 30D lookback for each week, not the sum of all 30D lookbacks for each day in that week.
  - Is there ever a use case for lookback metrics aggregating their aggregates? To me this seems like a capital B Bad Idea but I'd love to hear counterpoints

### SQL Mockup
Mockups in further comments

### Describe alternatives you've considered

Not supporting functionality

### Who will this benefit?

Anyone who has a metric that is not possible with our current metrics

### Are you interested in contributing this feature?

yes

**Comment by callum-mcdata** [comment]
### Date Join Option
I've tested this out and confirmed that it is possible to represent this behavior by changing the date join to reflect the range that you want to aggregate upon. It creates duplicate rows in bounded ranges to then aggregate on. The changes would be added to:
- `gen_base_query`: instead of a flat join on timestamp and date it would impose the lookback in the join

```sql
    select
        date_day,
        had_discount,
        sum(property_to_aggregate) as base_sum_metric,
        boolor_agg(metric_date_day is not null) as has_data
    from (

        select 
            cast(order_date as date) as metric_date_day, -- timestamp field
            calendar_table.date_day as date_day,
            -- ALL DIMENSIONS 
            had_discount,
            order_total as property_to_aggregate
        from DBT_TEST.DBT_METRICS_TESTING_SQL_GEN.fact_orders
        left join DBT_TEST.DBT_METRICS_TESTING_SQL_GEN.custom_calendar calendar_table
            on cast(order_date as date) >= date_day - interval '14 day'
            and order_date <= date_day
        where 1=1

    ) as base_query
    group by 1,2
```


### Windowing Option
I am actually removing this one from contention. While testing out the query, I found that the window function creates a lookback but only for the rows that are present in the base query. IE those days that have transactions and not following days that would also be included in the 14 day range.

We **could** use windowing here but then that would defeat the purpose of aggregating early because we'd have to aggregate again.

**Comment by visnup** [comment]
Hello! Has there been discussion about extending this feature to multiple possible windows of a single metric? Similar to possibly grain or maybe dimensions, we think of the rolling window of a single metric as having several different values sometimes: 7, 14, 28d. As is, we'd need to define different metrics for each one rather than a single one, called different ways via `metrics.calculate`.

Or, do you consider multiple windows an anti-pattern somehow?
